# Generated by Django 6.0.4 on 2026-04-14 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='SID', max_length=10)),
                ('stage', models.CharField(choices=[('D', 'Development'), ('Q', 'Quality'), ('T', 'Test'), ('P', 'Production'), ('S', 'Sandbox')], max_length=1)),
                ('virtual_hostname', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255)),
                ('instance_number', models.IntegerField()),
                ('tenant', models.CharField(blank=True, max_length=10, null=True)),
                ('is_rise', models.BooleanField(default=True)),
                ('last_synced', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('EXPORT', 'Export'), ('IMPORT', 'Import')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure')], default='PENDING', max_length=10)),
                ('du_name', models.CharField(max_length=255)),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('diff_text', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_system', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exports', to='delivery_units.system')),
                ('target_systems', models.ManyToManyField(related_name='imports', to='delivery_units.system')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
